version: '3'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDB
      MYSQL_USER: exampleUser
      MYSQL_PASSWORD: examplePassword
    ports:
      - 3307:3306
    volumes:
      - mysql8-storage:/var/lib/mysql
volumes:
  mysql8-storage:
