@baseurl = http://localhost:9081
@passangerUUID = ec9934aa-4414-4a03-9242-4fdb533715a0
@travelUUID = 8a66c9a5-3edc-4823-9779-7f5aa2adf914

## Create train
POST {{baseurl}}/v1/train HTTP/1.1
content-type: application/json

{
  "locomotiveModel": "another sample",
  "qtdWagons": 1234
}

###

##GET TRAIN
GET {{baseurl}}/v1/train/1 HTTP/1.1

###
@passengerPath = v1/passenger

## Create passanger
POST {{baseurl}}/{{passengerPath}} HTTP/1.1
content-type: application/json
Connection: Keep-Alive
 
{
  "name": "Nikolas Kakaroto",
  "email": "nikolas8@exemplo.com"
}

###

## Get passanger
GET {{baseurl}}/{{passengerPath}}/{{passangerUUID}} HTTP/1.1

###

## Get PassengerByE-mail
GET {{baseurl}}/{{passengerPath}}/email/nikolas8%40exemplo.com HTTP/1.1

###

## Create Route
POST {{baseurl}}/v1/route HTTP/1.1
content-type: application/json

{
  "destinyCity": "Viamão",
  "originCity": "Porto Alegre"
}

###

@travelPath = v1/travel
## Create travel
POST {{baseurl}}/{{travelPath}} HTTP/1.1
content-type: application/json

{
  "trainId": 1,
  "originCity": "Porto Alegre",
  "destinyCity": "Viamão",
  "departureDateTime": "19:31:00 02-06-2021",
  "arrivalDateTime": "19:35:00 02-06-2021"
}

###

## Get travel
GET {{baseurl}}/{{travelPath}}/{{travelUUID}} HTTP/1.1
