@baseurl = http://localhost:9081
@passangerUUID = 080eb6b3-a006-4813-936d-7749f981fee2

##Create train
POST {{baseurl}}/v1/train HTTP/1.1
content-type: application/json

{
  "locomotiveModel": "another sample",
  "qtdWagons": 1234
}

###

##GET TRAIN
GET {{baseurl}}/v1/train/1 HTTP/1.1

###

###Create passanger
POST {{baseurl}}/v1/passanger HTTP/1.1
content-type: application/json

{
  "name": "Nikolas Kakaroto",
  "email": "nikolas.freitas@exemplo.com"
}

###

###Get passanger
GET {{baseurl}}/v1/passanger/{{passangerUUID}} HTTP/1.1

