@baseurl = http://localhost:9081
@passangerUUID = "1234"

##Create train
POST {{baseurl}}/v1/train HTTP/1.1
content-type: application/json

{
  "locomotiveModel": "sample",
  "qtdWagons": 1234
}

###

##GET TRAIN
GET {{baseurl}}/v1/train/1 HTTP/1.1

###

###Create user
POST {{baseurl}}/v1/passanger HTTP/1.1
content-type: application/json

{
  "name": "Nikolas Kakaroto",
  "email": "nikolas.freitas@exemplo.com"
}

